library(gh)
library(base64enc)

# --- 1. Define configuration ---
repo_owner <- "niklz"
repo_name  <- "excess_impacts_national"
file_path  <- "data/ae_impacts.csv"  # Target path inside GitHub repo
branch     <- "main"
local_csv  <- "data/ae_impacts.csv"      # File generated by your analysis script

# --- 2. Run your analysis ---
# (Your calculation code runs here and outputs local_csv)
message("Calculation complete. Preparing to update GitHub...")

# --- 3. Get existing file SHA (Required by GitHub API for updates) ---
file_info <- gh(
  "GET /repos/{owner}/{repo}/contents/{path}",
  owner = repo_owner,
  repo  = repo_name,
  path  = file_path,
  ref   = branch
)
current_sha <- file_info$sha

# --- 4. Read local file & encode to Base64 ---
raw_bytes <- readBin(local_csv, "raw", file.info(local_csv)$size)
encoded_content <- base64encode(raw_bytes)

# --- 5. Push update to GitHub ---
gh(
  "PUT /repos/{owner}/{repo}/contents/{path}",
  owner   = repo_owner,
  repo    = repo_name,
  path    = file_path,
  message = "auto: update calculation dataset [skip ci]",
  content = encoded_content,
  sha     = current_sha,
  branch  = branch
)

message("Successfully pushed updated CSV to GitHub!")